Fix: Error: Exposing privileged or cross-origin callable is prohibited
Error: Exposing privileged or cross-origin callable is prohibited

Use of cloneInto to create obects witch accesibiility to target scope,
and waiveXrays to perform object calls

See: https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Language_Bindings/Components.utils.cloneInto
See: https://developer.mozilla.org/en-US/docs/Xray_vision

Also declares on prototype are not working.

These were added on Firefox 28, see:
https://bugzilla.mozilla.org/show_bug.cgi?id=964293
https://bugzilla.mozilla.org/show_bug.cgi?id=868675